spring.application.name=SpringHomework03
spring.datasource.url=jdbc:postgresql://localhost:5432/spring_test
spring.datasource.username=postgres
spring.datasource.password=030730
spring.datasource.driver-class-name=org.postgresql.Driver
server.port=8080

# MyBatis Configuration
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl